name: Update emulators

on:
  # TODO: enable schedule
  # schedule:
  #   # Run the first day of the month at a (more or less) random time
  #   - cron: '31 6 1 * *'

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-emulators:
    runs-on: ubuntu-latest

    env:
      # TODO: iterate over list of cores
      CORE_NAME=fceumm
      ROMFS_DIR=pkg/ctr/build/romfs

    steps:
      # TODO: store the latest version somewhere and determine whether a build is even necessary
      - name: Get latest version of RetroArch
        run: echo "RETROARCH_LATEST_VERSION=$(git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' https://github.com/libretro/RetroArch.git | tail -n 1 | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Fetch libretro-super
        run: git clone --depth 1 https://github.com/libretro/libretro-super.git

      # TODO: later, fetch more cores; maybe from a list stored in a .txt file?
      - name: Fetch core
        run: |
          cd libretro-super
          ./libretro-fetch.sh --shallow "$CORE_NAME"

      # Fetch RetroArch manually instead of using libretro-fetch.sh so that we can fetch the latest stable tag
      - name: Fetch RetroArch and dependencies
        run: |
          cd libretro-super
          git clone --depth=1 -b "$RETROARCH_LATEST_VERSION" https://github.com/libretro/RetroArch.git retroarch
          cd retroarch
          # From libretro-super/rules.d/player-rules.sh
          ./fetch-submodules.sh

      # TODO: later, build multiple cores; see https://docs.libretro.com/development/retroarch/compilation/3ds/#building-retroarch-in-bulk
      - name: Build core library
        run: |
          cd libretro-super
          docker run --rm -v "$PWD:/build" devkitpro/devkitarm sh -c "cd /build; ./libretro-build-ctr.sh $CORE_NAME"

      - name: Create and include RomFS in the core CIA
        run: |
          cd libretro-super/retroarch
          mkdir -p "$ROMFS_DIR"
          sed -i "s@TitleInfo:@RomFs:\n  RootPath                : $ROMFS_DIR\n\nTitleInfo2:@"  pkg/ctr/tools/template.rsf

      - name: Patch RetroArch to load ROM from RomFS
        run: |
          cd libretro-super/retroarch
          # Mount the RomFS at romfs:/
          sed -i 's/FILE_PATH_MAIN_CONFIG\(.*\)/FILE_PATH_MAIN_CONFIG\1\n\n   romfsInit();/' frontend/drivers/platform_ctr.c
          # Load the ROM at romfs:/rom.bin by default
          sed -i '0,/wrap_args->content_path\s.*=\s.*NULL/{s//wrap_args->content_path   = strdup("romfs:\/rom\.bin")/}' tasks/task_content.c
          sed -i 's/wrap_args->touched\s.*=\s.*false/wrap_args->touched        = true/' tasks/task_content.c
          # Create a dummy rom.bin file
          echo -n "nopi" > "$ROMFS_DIR"/rom.bin

      # TODO: is this needed?
      - name: Build salamander
        run: |
          cd libretro-super/retroarch
          docker run --rm -v "$PWD:/build" --network=host devkitpro/devkitarm sh -c "cd /build; make -f Makefile.ctr.salamander USE_CTRULIB_2=1"

      # TODO: build multiple cores
      - name: Build standalone core
        run: |
          cd libretro-super/retroarch
          cp "../dist/ctr/${CORE_NAME}_libretro_ctr.a" libretro_ctr.a
          docker run --rm -v "$PWD:/build" --network=host devkitpro/devkitarm sh -c "cd /build; make -f Makefile.ctr USE_CTRULIB_2=1"
